### ISSUE TITLE
Windows execution problem

### ISSUE THREAD

**Issue by fabiett0** [alexbruy/processing-taudem#5]
Hi,

I've installed processing-taudem in QGIS 3.2.1. 

When I try to execute a function within QGIS it suddendly terminate giving any error and producing any output.

However if I copy and paste the "TauDEM command" (as shown in the log tab) into the windows command prompt it works as expected.

this is an example of such a command:

`C:\Progra~1\MI564C~1\Bin\mpiexec -n 1 C:\Progra~1\TauDEM\TauDEM5Exe\pitremove -z C:/Users/fabio/Documents/mask_wgs84utm32n.tif -fel C:/Users/fabio/Documents/PitRemove.tif`

and this is the result I get within QGIS:

```
Risultati:
{'PIT_FILLED': <QgsProcessingOutputLayerDefinition {'sink':C:/Users/fabio/Documents/PitRemove.tif, 'createOptions': {'fileEncoding': 'System'}}>}
```

thanks,
Fabio

**Comment by alexbruy** [comment]
Can you provide full execution log from the Processing algorithm "Log" tab? Can you confirm that after execution of the algoritm no outputs created, e.g. there are no files in the temp directory or in the path you used for output?

**Comment by fabiett0** [comment]
alex, thanks for replying!

here's the full log:

```
Processing algorithm…
Algorithm 'Pit remove' starting…
Parametri in ingresso:
{ 'DEPRESSION_MASK' : None, 'ELEVATION' : 'C:/Users/fabio/Documents/mask_wgs84utm32n.tif', 'FOUR_NEIGHBOURS' : False, 'PIT_FILLED' : 'C:/Users/fabio/Documents/PitRemovedMask.tif' }

TauDEM command:
C:\Progra~1\MI564C~1\Bin\mpiexec -n 1 C:\Progra~1\TauDEM\TauDEM5Exe\pitremove -z C:/Users/fabio/Documents/mask_wgs84utm32n.tif -fel C:/Users/fabio/Documents/PitRemovedMask.tif
TauDEM command output:
Esecuzione completata in 0.07 secondi
Risultati:
{'PIT_FILLED': <QgsProcessingOutputLayerDefinition {'sink':C:/Users/fabio/Documents/PitRemovedMask.tif, 'createOptions': {'fileEncoding': 'System'}}>}

Caricamento layer
I seguenti layers non sono stati caricati correttamente<ul><li>C:/Users/fabio/Documents/PitRemovedMask.tif</li></ul>Puoi verificare il "Pannello dei messaggi" nella finestra principale di QGIS per trovare maggiori informazioni circa l'esecuzione dell'algoritmo
```

I confirm that no output was created, also the execution terminate istantaneously, while it actually requires some seconds when launched manually.

I provided the full path of the executables in the configuration form.

Thanks,
Fabio

**Comment by alexbruy** [comment]
Are there anything in the QGIS message log?

**Comment by fabiett0** [comment]
nope!

**Comment by alexbruy** [comment]
I have looked into this issue and there is nothing related to the plugin here. The problem is with TauDEM distribution: TauDEM programs are linked to the GDAL library but TauDEM's "Complete Windows installer" installs TauDEM files and GDAL libraries in different directories. As result, when you try to call TauDEM in the clean environment (as in QGIS/OSGeo4W environment) TauDEM just can't find required GDAL libs. You can easliy check this by executing any command from the OSGeo4W shell.

As workaround you can copy all DLL's from the TauDEM's GDAL directory to the directory where TauDEM executables are located. But proper solution would be to ask TauDEM deveopers to make proper installer where dependencies like GDAL installed into same directory as executabled, making it possible to run them in the clean environment.
